-intstyle "ise" -incremental -lib "secureip" -o "/home/pablo384/Documents/FPGA/ISE/proyectoFInal/tb_u3_isim_beh.exe" -prj "/home/pablo384/Documents/FPGA/ISE/proyectoFInal/tb_u3_beh.prj" "work.tb_u3" 
